#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 21 18:08:13 2019

@author: constanzamunoz
"""

import numpy as np
import matplotlib.pyplot as plt

t0 = 0
Ri = 1.7*1e10 #m
vi = 0 #m s-1
Pi = 5.6*1e4 # N m-2
dt = 1e4  #s
gamma = 5/3 
M = 1e31 #kg
m = 1e26  #kg
G = 6.674* 1e-11 #N m2 Kg-2

vf = vi + ((4 *np.pi* (Ri**2)*Pi)/m
           - (G*M)/(Ri**2))*dt

Rf = Ri + (vf*dt)
Pf = (Pi*(Ri**(3*gamma)))/(Rf**(3*gamma))

R = np.array([])
t = np.array([])
v = np.array([])
P = np.array([])

R = np.append(R, Ri)
R = np.append(R, Rf)
t = np.append(t, t0)
t = np.append(t, (t0+dt))
v = np.append(v, vi)
v = np.append(v, vf)
P = np.append(P, Pi)
P = np.append(P, Pf)

int = 1 
while int <= 150:
    vi = vf
    Ri = Rf
    Pi = Pf
    time = t0 +dt
    vf = vi + ((4 *np.pi* (Ri**2)*Pi)/m
           - (G*M)/(Ri**2))*dt
    Rf = Ri + (vf*dt)
    Pf = (Pi*(Ri**(3*gamma)))/(Rf**(3*gamma))
    R = np.append(R, Rf)
    t = np.append(t, (time))
    v = np.append(v, vf)
    P = np.append(P, Pf)
    t0 = time
    int = int +1

R_sun = 6.95700*1e8

plt.figure(figsize=(7,5))
"""
plt.plot(t/dt,R/R_sun, marker='o', ms=6, mfc='red')
plt.ylabel(r'Radius $[R_{\odot}]$',fontsize=16)
plt.xlabel(r'Time [$10^{4}$ s]',fontsize=16)
plt.legend()
plt.savefig("Radius.png")

plt.plot(t/dt,v/1000, marker='o', ms=6, mfc='blue')
plt.xlabel(r'Time [$10^{4}$ s]',fontsize=16)
plt.ylabel(r'Velocity [$km s^{-1}$]',fontsize=16)
plt.savefig("velocity.png")
"""
plt.plot(t/dt,P/1e6, marker='o', ms=6, mfc='green')
plt.xlabel(r'Time [$10^{4}$ s]',fontsize=16)
plt.ylabel(r'Pressure [$10^{6}$ N $m^{-2}$]',fontsize=16)
plt.savefig("pressure.png") 
